name: PHP Linting (WordPress Coding Standards, PHPCS/PHPCBF)

on: [push, pull_request]

jobs:
  phpcs-phpcbf:
    name: Run PHPCS and PHPCBF
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          tools: composer

      - name: Install dependencies
        run: composer install --no-scripts --no-progress --no-suggest

      - name: Run PHPCS
        run: composer phpcs

      - name: Run PHPCBF
        run: composer phpcbf
